### ISSUE TITLE
Lidarr sometimes fails to load dependency libraries

### ISSUE THREAD

**Issue by formeo14** [TrevTV/Lidarr.Plugin.Deezer#1]
Hello,

I tired to use your fork of the Deezer Lidarr plugin. Unfortunately, it appears that the current implementation of DeezNET is causing Lidarr to encounter a "not found" issue and breaks it:"[Info] Bootstrap: Starting Lidarr - /app/bin/Lidarr - Version 2.5.2.4317
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Debug] Bootstrap: Console selected
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Warn] Bootstrap: Error starting with plugins enabled
[v2.5.2.4317] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'AngleSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea'. An operation is not legal in the current state. (0x80131509)
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
at System.Reflection.RuntimeAssembly.get_DefinedTypes()
System.IO.FileLoadException: Could not load file or assembly 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'
---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly)
at NzbDrone.Common.Composition.PluginLoadContext.Load(AssemblyName assemblyName) in ./Lidarr.Common/Composition/PluginLoadContext.cs:line 24
at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.IO.FileLoadException: Could not load file or assembly 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'
---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly)
at NzbDrone.Common.Composition.PluginLoadContext.Load(AssemblyName assemblyName) in ./Lidarr.Common/Composition/PluginLoadContext.cs:line 24
at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.IO.FileLoadException: Could not load file or assembly 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'
---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly)
at NzbDrone.Common.Composition.PluginLoadContext.Load(AssemblyName assemblyName) in ./Lidarr.Common/Composition/PluginLoadContext.cs:line 24
at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.IO.FileLoadException: Could not load file or assembly 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'
---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly)
at NzbDrone.Common.Composition.PluginLoadContext.Load(AssemblyName assemblyName) in ./Lidarr.Common/Composition/PluginLoadContext.cs:line 24
at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.IO.FileLoadException: Could not load file or assembly 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DeezNET, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'
---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly)
at NzbDrone.Common.Composition.PluginLoadContext.Load(AssemblyName assemblyName) in ./Lidarr.Common/Composition/PluginLoadContext.cs:line 24
at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.IO.FileLoadException: Could not load file or assembly 'AngleSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea'. An operation is not legal in the current state. (0x80131509)
File name: 'AngleSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea'
---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly)
at NzbDrone.Common.Composition.PluginLoadContext.Load(AssemblyName assemblyName) in ./Lidarr.Common/Composition/PluginLoadContext.cs:line 24
at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
at DryIoc.Portable.<>c__DisplayClass2_0.<GetAssemblyTypesMethod>b__0(Assembly a) in /_/src/DryIoc/Container.cs:line 15489
at DryIoc.Portable.GetAssemblyTypes(Assembly a) in /_/src/DryIoc/Container.cs:line 15478
at DryIoc.Registrator.GetImplementationTypes(Assembly assembly) in /_/src/DryIoc/Container.cs:line 7891
at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
at DryIoc.Registrator.RegisterMany(IRegistrator registrator, IEnumerable`1 implTypes, Func`2 getServiceTypes, Func`2 getImplFactory, Func`3 getServiceKey, Nullable`1 ifAlreadyRegistered) in /_/src/DryIoc/Container.cs:line 7938
at DryIoc.Registrator.RegisterMany(IRegistrator registrator, IEnumerable`1 implTypes, IReuse reuse, Made made, Setup setup, Nullable`1 ifAlreadyRegistered, Func`2 serviceTypeCondition, Boolean nonPublicServiceTypes, Object serviceKey) in /_/src/DryIoc/Container.cs:line 8023
at DryIoc.Registrator.RegisterMany(IRegistrator registrator, IEnumerable`1 implTypeAssemblies, Func`2 serviceTypeCondition, IReuse reuse, Made made, Setup setup, Nullable`1 ifAlreadyRegistered, Boolean nonPublicServiceTypes, Object serviceKey) in /_/src/DryIoc/Container.cs:line 8015
at NzbDrone.Common.Composition.Extensions.ServiceCollectionExtensions.AutoAddServices(IContainer container, List`1 assemblies) in ./Lidarr.Common/Composition/Extensions.cs:line 26
at NzbDrone.Host.Bootstrap.<>c__DisplayClass8_0.<CreateConsoleHostBuilder>b__1(IContainer c) in ./Lidarr.Host/Bootstrap.cs:line 225
at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass10_0`1.<ConfigureContainer>b__0(HostBuilderContext context, TContainerBuilder builder)
at Microsoft.Extensions.Hosting.Internal.ConfigureContainerAdapter`1.ConfigureContainer(HostBuilderContext hostContext, Object containerBuilder)
at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
at Microsoft.Extensions.Hosting.HostBuilder.Build()
at NzbDrone.Host.Bootstrap.RunBuilder(IHostBuilder builder, Boolean usePlugins) in ./Lidarr.Host/Bootstrap.cs:line 150"

Could this be due to a missing entry in NuGet.config file that references the DeezerNET library? What might be the underlying cause of this problem?

**Comment by TrevTV** [comment]
Surprised someone is already trying the plugin lol. This issue has been an odd one, but I believe it has to do with Lidarr itself and not DeezNET as Lidarr's plugin system doesn't seem to properly load dependencies of plugins. I've been trying to find an in-plugin solution but have yet to get something that works, the only functional solution I've found is to manually modify the PluginManager inside Lidarr.Common to force-load dependencies. Will update this issue in case I find an actual solution.

**Comment by formeo14** [comment]
That was a fast response.
I found the version from ta264 yesterday, but it has an issue. I'm encountering the "DeemixDownloadProtocol is not enabled for this artist" error. And if there is an error search for forks!

OK you are using a modified version of Lidarr. However, I prefer not to create a custom version myself as I intend to run it on Docker on my server and would rather avoid the maintenance hassle. I initially thought the issue might be due to the package indexing [here](https://github.com/TrevTV/Lidarr.Plugin.Deezer/blob/master/src/NuGet.config), but since I haven't built a Lidarr plugin before, I'm unsure about the potential challenges or the implementation details. As Plugins are not yet available on the master branch.

I know that the problem is not be related to your DeezNET library, which I find quite impressive But on this repo there were no issue tab. 
Is the the issue with the HTML parsing due to HtmlAgilityPack, or your method of scraping ARL's from firehownk? I personally use AngleSharp for scraping websites instead of HtmlAgilityPack, so I don't know.

**Comment by TrevTV** [comment]
I believe that error ("DeemixDownloadProtocol is not enabled for this artist") is actually due to the Deemix delay profile being disabled. If you go into Settings -> Profile -> Delay Profile, click the wrench, then enable "Deemix" in the Edit Delay Profile modal, it should work (the same is true for this plugin as well I believe, just with Deezer instead of Deemix).

I'd also rather not use a modified version of Lidarr for the same reasons, it was primarily for testing to see if I found the actual cause of the issue. I'm not actually sure if that NuGet configuration is related or not, I don't have any former experience with Lidarr or it's source code so this has been a guessing game for me.

I previously used HtmlAgilityPack which threw that error, then I switched to AngleSharp which worked until I installed the plugin on my server and began throwing the same error but for AngleSharp this time.

I believe I've found some kind of a solution (merging all dependencies into a single plugin DLL), not ideal, but it's much better than having to modify Lidarr itself. I'm going to try to automate the process and make a new release at some point soon.

**Comment by TrevTV** [comment]
[Newest release](https://github.com/TrevTV/Lidarr.Plugin.Deezer/releases/tag/10.0.0.27046) should hopefully work fine.

Make sure you enabled the Deezer delay profile as I mentioned in the last comment or else you'll get the same error as the Deemix plugin.

I'd also make sure you have Rename Tracks enabled under Media Management if you don't already as it prevents all tracks from getting thrown directly under the artist folder rather than each album having their own folder.

**Comment by formeo14** [comment]
Works thank you
