### ISSUE TITLE
No results found.

### ISSUE THREAD

**Issue by lightsout** [TrevTV/Lidarr.Plugin.Deezer#4]
I went through the install guide and triple checked everything. Got the indexer and download client set up for deezer. But I cannot seem to get any results when I search for an album. I removed all other indexers and download clients to simplify things. Also used my own arl and allowed the app to choose one. Neither getting any results.

**Comment by TrevTV** [comment]
What albums are you searching for? With my regular test albums, I am able to search just fine.

**Comment by lightsout** [comment]
> What albums are you searching for? With my regular test albums, I am able to search just fine.

I tried "Green Day". Figured that was very mainstream. Also tried "Drake". None of his albums come up. When I hit the auto search button it immediately says "no results". Interactive brings up nothing as well. (for reference I also installed your tidal plugin after this and that is  bringing up results)

**Comment by lightsout** [comment]
`[Info] ReleaseSearchService: Searching indexers for [Drake - For All the Dogs (2023)]. 0 active indexers 
[Info] DownloadDecisionMaker: No results found 
[Info] RssSyncService: Starting RSS Sync 
[Warn] FetchAndParseRssService: No available indexers. check your configuration. 
[Info] DownloadDecisionMaker: Processing 1 releases 
[Info] RssSyncService: RSS Sync Completed. Reports found: 1, Reports grabbed: 0 
[Error] EventAggregator: PendingReleaseService failed while processing [RssSyncCompleteEvent] 

[v2.9.0.4506] System.ApplicationException: Expected query to return 1 rows but returned 0
   at NzbDrone.Core.Datastore.BasicRepository`1.Get(IEnumerable`1 ids) in ./Lidarr.Core/Datastore/BasicRepository.cs:line 121
   at NzbDrone.Core.Music.ArtistService.GetArtists(IEnumerable`1 artistIds) in ./Lidarr.Core/Music/Services/ArtistService.cs:line 216
   at NzbDrone.Core.Download.Pending.PendingReleaseService.IncludeRemoteAlbums(List`1 releases, Dictionary`2 knownRemoteAlbums)
   at NzbDrone.Core.Download.Pending.PendingReleaseService.GetPendingReleases() in ./Lidarr.Core/Download/Pending/PendingReleaseService.cs:line 258
   at NzbDrone.Core.Download.Pending.PendingReleaseService.RemoveRejected(List`1 rejected) in ./Lidarr.Core/Download/Pending/PendingReleaseService.cs:line 452
   at NzbDrone.Core.Download.Pending.PendingReleaseService.Handle(RssSyncCompleteEvent message) in ./Lidarr.Core/Download/Pending/PendingReleaseService.cs:line 498
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)


[Info] ReleaseSearchService: Searching indexers for [Drake - Honestly, Nevermind (2022)]. 0 active indexers 
[Info] DownloadDecisionMaker: No results found 
`

**Comment by TrevTV** [comment]
Honestly not sure what is happening on your end, both Drake albums are showing up in my search (ignore the error mark,  I didn't have my test setup completely configured)
![image](https://github.com/user-attachments/assets/7551c573-e6ec-498b-a439-af8e97b29733)
![image](https://github.com/user-attachments/assets/de04521c-1315-48cf-9d59-77f9fcb5e217)

**Comment by lightsout** [comment]
I got it. User error (of course :) ) 
I had set a tag for some reason in the indexer and misunderstood its purpose. All is well now. Thanks this is an awesome addition to Lidarr.
